---

name: Run CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  lint-multi-os-python-poetry:
    name: Lint ${{ matrix.os }} | ${{ matrix.python-version }} | ${{ matrix.poetry-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.0, 1.1.2]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install packages
        run: poetry install
      - name: run black
        run: poetry run black . --check
      - name: run flake8
        run: poetry run flake8

  test-multi-os-python-poetry:
    name: Test ${{ matrix.os }} | ${{ matrix.python-version }} | ${{ matrix.poetry-version }}
    runs-on: ubuntu-18.04
    needs: [lint-multi-os-python-poetry]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.0, 1.1.2, 1.1.4]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install packages
        run: poetry install
      - name: run pytest
        run: poetry run pytest
  
  code-coverage:
    name: run code coverage
    runs-on: ubuntu-18.04
    needs: [test-multi-os-python-poetry]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: install packages
        run: poetry install
      - name: run coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml -o coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          flags: unittests
